### PR TITLE
refactor activities page to use a calendar

### PR DESCRIPTION
**Pull request by RignonNoel**
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | Enhancement
| Tickets (_issues_) concerned               | [74](https://genielibre.com/issues/74)

---

## What have you changed ?
Refactor `activities` page to use a calendar in place of the table of all events

## How did you change it ?
 - Integration of a new calendar component
 - Refactor the page

## Screenshots
screenshot-2018-6-10 volontaria 3
screenshot-2018-6-10 volontaria 4

## Verification :
 -  [x] My branch name respect the standard defined in `CONTRIBUTING.md`
 -  [x] This Pull-Request fully meets the requirements defined in the issue
 -  [ ] I added or modified the attached tests

### CODE REVIEW

**Comment by RignonNoel** [comment]
I'm okay with you about the color explanation but unfortunately i'm really not good in computer graphics. We will need a volunteer to made us a `Benevolometre`.

# New version of the page :
screenshot-2018-6-12 volontaria

**Comment by RignonNoel** [comment]
## New deisgn with benevolometre
screenshot-2018-6-12 volontaria 2

## `:hover` of one section of benevolometre
screenshot from 2018-06-12 14-10-16

**Comment by yanicolivier** [comment]
I like the 'Bénévolomètre' :)

Some little orthographical changes suggested : 
- 'Laisse-toi' add -
- 'Bénévolomètre' replace e to è
- 'ton implication ?' remove space before ?

- I'm wandering if the arrow is necessary. 
- Also now when I click on a dot, nothing happen I would suggest having the same behaviour as clicking on the calendar tile if there is no extra functionalities.

**Comment by RignonNoel** [comment]
- [x] 'Laisse-toi' add -
 - [x] 'Bénévolomètre' replace e to è
 - [x] 'ton implication ?' remove space before ?
 - [ ] I'm wandering if the arrow is necessary.
   - I've check some idea of design with people at my home and people choosed this one with the arrow. I'm really not closed minded to change it if you have a better idea. I think it could be a good group brainstorming next meeting.
 -  [ ] Also now when I click on a dot, nothing happen I would suggest having the same behaviour as clicking on the calendar tile if there is no extra functionalities.
  - I did'nt find a way to do that for the moment, it's why i just remove the link. I will continue to check but i think it's an overthough problem and people will not see that.

**Pull request merged**
