### PR TITLE
add non_field_errors on forgot password form

### PR DESCRIPTION
**Pull request by RignonNoel**
| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      | Fix
| Tickets (_issues_) concerned               | None

---

## What have you changed ?
Add generic error message for `non_field_errors` from API

## How did you change it ?
Just add an alert box on the top of the form and a condition on the request response logic.

## Verification :
 -  [x] My branch name respect the standard defined in `CONTRIBUTING.md`
 -  [x] This Pull-Request fully meets the requirements defined in the issue
 -  [ ] I added or modified the attached tests

### CODE REVIEW

**Comment by RignonNoel** [comment]
The lack of message in the error area is related to a bug in the API because ALL message from API may be in an array :
https://github.com/Volontaria/API-Volontaria/blob/13b0b5a70547d654c619e04f7fef2c2d882df22b/source/apiVolontaria/apiVolontaria/views.py#L292

**Comment by RignonNoel** [comment]
I add a condition on the button and i made an enhancement of the error display message (new icons, new size of text)

**Comment by yanicolivier** [comment]
The condition is only working the first time.  If I type a letter and erase it to go back to empty the button stay active.  Also I would add the same kind of condition on the new password form (Empty or error with grey button).  The error message is display in english if searching for a non existing user.

**Comment by RignonNoel** [comment]
> The condition is only working the first time. If I type a letter and erase it to go back to empty the button stay active.

Yes it was just to not frustrate user and allow him to see a detailled error message if he want to put nothing. The defautl state as disabled was just to help user to understand the page.

> Also I would add the same kind of condition on the new password form (Empty or error with grey button). 

Finally i've removed the disabled state and put default error message on both form if you submit with nothing. I did a lot of research and testing for the blind lately and this way of doing things are more easy for everyone.

> The error message is display in english if searching for a non existing user.

Yes it's a problem from the API, as i said i work on it in this new PR : Volontaria/API-Volontaria#206

**Comment by RignonNoel** [comment]
I close this PR since it's out of date since a long time.

Feel free to update this PR and to reopen it.

**Pull request closed without merging**
